### ISSUE TITLE
Verify/fix servo references in orchestra demo tutorial

### ISSUE THREAD

**Issue by brianhinch** [googlearchive/ChromeWebLab#42]
[the docs](https://github.com/GoogleChrome/ChromeWebLab/blob/hardware-tutorials-dev/Orchestra/hw/tutorial/Readme.md) should include these checks/edits:
- Is the correct servo voltage 6v or 7.4v?
- Which type of arm should be attached to the servo spindle?
- Are any adaptors/modifications to the cable used to connect to the arduino?

**Comment by mmansion** [comment]
I've updated the readme to include a note at the bottom of the spec indicating we used 7.4v. In the parts list it mentions 6v, which is more of a standard, so I think we can leave that part.

@justincouch what is the servo spindle arm?  I can't quite tell from the video.

I don't think we did anything special to connect to the arduino other than tin the tips of the wires for easy insertion. We can make a note of that.
