### ISSUE TITLE
Make SketchBots mobile friendly

### ISSUE THREAD

**Issue by PaulKinlan** [googlearchive/ChromeWebLab#51]
TODO we can split these out if needs be:
- [ ] Define the viewport
- [x] Define the breakpoints for the media queries
- [x] Check it all works with Touch (you can emulate this on a desktop in Chrome DevTools)
- [x] Create the UI for the appropriate break points.

Currently the Sketchbot looks like this on a desktop: 

![screen shot 2013-08-13 at 6 42 47 pm](https://f.cloud.github.com/assets/45510/956567/40bcd9a0-0440-11e3-8b7e-ccf445b59baa.png)

However, on a mobile screen it is all cut-off

![screen shot 2013-08-13 at 6 45 33 pm](https://f.cloud.github.com/assets/45510/956578/5b1111c2-0440-11e3-8c02-1eeb128ce463.png)

I am not quite sure how it should appear on mobile yet, so comments should include screen shots.

**Comment by michaelsanford** [comment]
This narrow three-column interface seems already well-suited to a small portrait viewport: break the above three columns into self-contained, (nearly) full-viewport panels.

![sketchbot mobile proposal 1](https://f.cloud.github.com/assets/1800499/963991/456468ec-050d-11e3-8da2-f426da0d358a.png)

Given this, the next decision is navigation. I see two options:
- A variant of the [Android Swipe View](http://developer.android.com/design/patterns/swipe-views.html) pattern should work well here (essentially scrolling to fixed breakpoints — [mobile-friendly libraries](https://github.com/chrisvoll/snapscroll) exist, rolling from scratch shouldn't be difficult).
- Automatically advance through/replace views as the sketch progresses through queued to being drawn to completed. This would only really be appropriate for users queueing one sketch at a time, though, which may be undesirable. This pattern would probably work better as an SPA.

**Comment by PaulKinlan** [comment]
Looks really nice! 

One thing I am worried about is that a user would lose track of where the images have gone in a tabbed view... I suppose it could be indicated with a visual flash or status number update.

What about a vertical accordion stack? Or a slide out menu tray with the sections in (then it might be quite close to your diagrams then)

**Comment by PaulKinlan** [comment]
I meant to add that the reason why auto advance might not work is that there could be a queue of images being taken and being processed at the same time...

**Comment by PaulKinlan** [comment]
Http://weight.awrotwist.com has a nice slide out menu (I goes out too far IMO for this project but highlights the idea)

**Comment by michaelsanford** [comment]
@PaulKinlan Indeed, not being able to queue multiple pictures was a caveat of auto-advancing. Just throwing it out there…

Aerotwist's slide-out is kind of nice. So, you envision something like this (smaller, menu selection closes tray)?

![moq_2 2](https://f.cloud.github.com/assets/1800499/968985/91a341b8-05b4-11e3-9fcd-42d8c5b80260.png)

**Comment by PaulKinlan** [comment]
This looks brilliant. Let's do this layout. (Sorry for the delay in replying currently on vacation this week)

**Comment by michaelsanford** [comment]
Thanks @PaulKinlan. You can assign that to me (if you're using that workflow) and I'll get right on it.

Don't worry about response times: I'm not on vacation but thus have the same problem ;)

**Comment by michaelsanford** [comment]
Finally getting this moving.

After some experimentation, I decided to go with the following maximal `width` breakpoints:

#### > 960

Existing, since that's the existing fixed width of the desktop interface before horizontal scrolling (with existing margins). This also captures most tablets in landscape orientation, which will scroll vertically (which should be fine).

#### 801px — 960px

Captures reduced window/device dimensions while still presenting a pleasant desktop version (largely through slightly reduced margins, widths).

#### 800px

Nexus 7 (for example) is 800px wide in portrait mode. I figure on that and smaller we want the above mobile interface.

I'll post some screenshots when I get the last bit done. I don't mind waiting for that point for comments, unless someone sees a big problem already). Ref: My [fork feature branch](https://github.com/michaelsanford/ChromeWebLab/tree/sketch-mobile-ui).

**Comment by PaulKinlan** [comment]
When setting width=device-width I am not sure nexus7 (2012) comes out as 800px.

**Comment by PaulKinlan** [comment]
But otherwise things genearlly seem reasonable.  Look forward to seeing what is done. :)

**Comment by michaelsanford** [comment]
@PaulKinlan You might be right, I haven't done too much testing yet (just going by the spec, and using it as a rough estimate for what we might look for in terms of interface transitions).

I'll post some screenshots when I have some more to show.

**Comment by PaulKinlan** [comment]
@michaelsanford awesome, looking forward to seeing them.

**Comment by michaelsanford** [comment]
Here's a simulated Nexus 4 (tested in Canary 31.0.1622.0). I have to work out a few small quirks, lint and performance profile, but here's something to look at, at least.

I wonder that the horizontal pipes are not obviously a menu disclosure trigger (particularly in this orientation). the trigger hides when in desktop mode. What do we think about increasing the button size ( _New From…_, _View…_ )?

Bring out 'yer comments!

![waiting](https://f.cloud.github.com/assets/1800499/1092743/4b820fb2-1689-11e3-8c8c-cda67d9b74e0.png)

![menu](https://f.cloud.github.com/assets/1800499/1092744/4fb48cd6-1689-11e3-8172-361bd41c746b.png)

![completed](https://f.cloud.github.com/assets/1800499/1092745/53bfedc0-1689-11e3-8e72-35eb94c67b24.png)

![waiting landscape](https://f.cloud.github.com/assets/1800499/1092769/7b34cbb8-168a-11e3-834c-633196e3d663.png)

Worth reminding: currently, [Safari iOS and Chrome vanilla don't support WebGL](http://caniuse.com/webgl) (which causes `Three.js` to fail to create a context in which to do anything). So, this app is likely (currently) limited to Opera Mini, FireFox, and Chrome Android via flags.

**Comment by PaulKinlan** [comment]
Awesome work.

re:three.  I believe this was only ever used for the background image, to make it curve.

re:screenshots.  These are look great!  I would change the menu icon to be the burger menu icon people are using nowadays, and have it positioned further up on the top left.  We will probably have to sort out the logo and get it moved..... I would be open to making the logo the "toggle", but I am not sure how discoverable that is.

The "new from *" buttons, we should make them full width and bump up the font size.  I would also make each of the white photo holders full width too.

**Comment by michaelsanford** [comment]
Thanks for the feedback @PaulKinlan ; I'll integrate it!

I'll also have a look at mitigating `Three.js`'s killing Safari iOS, if it's not really necessary.

**Comment by michaelsanford** [comment]
## Design

Bigger buttons everywhere, here are a few more views. Again, an emulated Nexus 4.

### Webcam (Portrait)

![portrait capture](https://f.cloud.github.com/assets/1800499/1103746/67badf9e-18c1-11e3-873e-06876c2d06c9.png)

### Webcam (Landscape)

![landscape capture](https://f.cloud.github.com/assets/1800499/1103769/d49fd6c2-18c2-11e3-800a-a99e9964a235.png)

### Using a file

![portrait file](https://f.cloud.github.com/assets/1800499/1103747/67c1b8e6-18c1-11e3-8c4d-d5311653ff30.png)

### In progress

![portrait in progress](https://f.cloud.github.com/assets/1800499/1103748/67c27d6c-18c1-11e3-8744-9614772c0f99.png)

### Completed

![completed](https://f.cloud.github.com/assets/1800499/1103749/67c42162-18c1-11e3-9281-cdeb09b96907.png)

### Better menu trigger?

@PaulKinlan How about we use the mobile menu trigger Maps Android is now using (maintain brand-consistent UI)? Something like this:
![New Mobile Menu trigger](https://f.cloud.github.com/assets/1800499/1103764/352aea3c-18c2-11e3-84cb-9228541ab401.png)

**Comment by PaulKinlan** [comment]
This is looking awesome.

**Comment by PaulKinlan** [comment]
@michaelsanford the thing I just merged, was I supposed to merge it?  I am looking at the code and I don't see anything mobile :)

**Comment by michaelsanford** [comment]
@PaulKinlan I just checked out the [merge](https://github.com/GoogleChrome/ChromeWebLab/commit/7ee818ea644f6610b730a95a2b889129074ab914) and it looks like you _did_ get everything relevant from my leafpile (with bbab7cf and 59ad9a4):
1. ChromeWebLab/Sketchbots/sw/ui/view/RobotsView.css [Mods start here](https://github.com/GoogleChrome/ChromeWebLab/blob/master/Sketchbots/sw/ui/view/RobotsView.css#L367)
2. ChromeWebLab/Sketchbots/sw/ui/controller/RobotsMainController.js [Mods start here](https://github.com/GoogleChrome/ChromeWebLab/blob/master/Sketchbots/sw/ui/controller/RobotsMainController.js#L71)
3. ChromeWebLab/Sketchbots/sw/ui/view/RobotsViewStrings.js [Added navigation header](https://github.com/GoogleChrome/ChromeWebLab/blob/master/Sketchbots/sw/ui/view/RobotsViewStrings.js#L73)
4. ChromeWebLab/Sketchbots/sw/ui/controller/RobotsTopicQueuesController.js [Added some properties](https://github.com/GoogleChrome/ChromeWebLab/blob/master/Sketchbots/sw/ui/controller/RobotsTopicQueuesController.js#L301)

I just cloned Google's master and it seems to be working for me:
![screen shot 2013-09-18 at 9 36 23 am](https://f.cloud.github.com/assets/1800499/1165150/806ba868-2067-11e3-80a5-cf092e0090d2.png)

I'd note that the width breakpoint for the stuff pictured above is 615px, so most tablets in landscape (many in portrait, too) will get the desktop-looking one with narrower margins. Easily improved, I was just eager to push something upstream so you can finally play with it.

**Comment by PaulKinlan** [comment]
I might have made a schoolboy error and not updated my local copy....

**Comment by PaulKinlan** [comment]
/me hangs head in shame.

@michaelsanford thanks for all this work by the way!  I am going to start promoting it more!!  

I will start making separate issues for things that I find now and you (if you want), me, or anyone in the community can pick them up.

For instance, I can't see a viewport meta element - we need this. <meta name="viewport" content="width=device-width">

**Comment by michaelsanford** [comment]
@PaulKinlan It was a lot of fun and I'm definitely still interested in continuing my involvement.

_Woops_, I did neglect the viewport! I'll add it.

As a side-note, one of my primary volunteer projects is running a robotics competition for high-school students. I'm pushing to deploy one of these at the competition this year, just for fun.
