### ISSUE TITLE
Add pre-commit hook for grunt-jsbeautifier

### ISSUE THREAD

**Issue by JakeChampion** [googlearchive/ChromeWebLab#53]
Shall we add a pre-commit hook to make sure the project is adhering to the style guide before it gets committed?

Very trivial to implement but good to keep consistency in the project's codebase

**Comment by PaulKinlan** [comment]
I like the idea.  Let's do it.  Will need to keep project dependicies up to date as we need to check if node is installed etc.

**Comment by PaulKinlan** [comment]
@JakeChampion is this something that you would be able to do?

**Comment by JakeChampion** [comment]
@PaulKinlan I got around to doing this today, apologies for the delay.

**Comment by JakeChampion** [comment]
merged
