### ISSUE TITLE
Instantiate CanvasRenderer where WebGL is unavailable in Sketchbot.

### ISSUE THREAD

**Issue by michaelsanford** [googlearchive/ChromeWebLab#70]
Three.js can't initialize a WebGL context [on iOS or Chrome Android (Stable)](http://caniuse.com/#feat=webgl), so it bugs and kills the page. This feature is used by the gcode-viewer.

Instead, `THREE.CanvasRenderer` must be instantiated in place of `THREE.WebGLRenderer`. I have it working in a quick test (Safari in the iOS 7 Simulator and Chrome Shell on the Android 4.3 emulator).
- [x] Elegantly implement [Three.js' WebGL detector](https://github.com/mrdoob/three.js/blob/master/examples/js/Detector.js)?

And then integrate into:
- [x] Sketchbots/sw/labqueue/static/ui/controller/libs/contrib/gcode/gcode-viewer-mootools.js
- [ ] _others?_

(Got this one.)

**Comment by PaulKinlan** [comment]
Sounds great!  I don't recall any other places where it is used.  On the original project the background image used to be WebGL, but I can't remember if we do this any more.

**Comment by michaelsanford** [comment]
I patched it so the app will at least function on a mobile device. Quick fix.

I'll take a look at refactoring that bit, possibly removing it entirely if it's unused.

**Comment by michaelsanford** [comment]
My quick fix is a modified fragment of what the above-mentioned detector uses.

I'll get to refactoring it next, and remove it if necessary. It seems to work on Chrome Test Shell, Android 4.3 / Nexus 4 in the emulator.
